### ISSUE TITLE
Use UIImage.SymbolConfiguration instead of UIImage.Configuration

### ISSUE THREAD

**Issue by edwinveger** [SFSafeSymbols/SFSafeSymbols#41]
The convenience initializers for UIImage expect a `UIImage.Configuration` object. But isn't this object kind of meaningless in the context of SFSymbols? As a user I want to pass `UIImage.SymbolConfiguration` instead, right?

https://github.com/piknotech/SFSafeSymbols/blob/31a99db357f2b839a18ab598c4aa87a741bd6009/Sources/SFSafeSymbols/Initializers/UIImageExtension.swift#L23-L25

**Comment by fredpi** [comment]
@edwinveger Thanks for pointing this out!

It would somehow make sense to change that, but the "official" Apple initializer (that _SFSafeSymbols_ is replicating) also uses `UIImage.Configuration` instead of `UIImage.SymbolConfiguration`:

```swift
public init?(systemName name: String, withConfiguration configuration: UIImage.Configuration?)
```

I think there's also a use case for this more generic initializer: Copying the configuration of another symbol image:

```swift
let myConfig = UIImage.SymbolConfiguration(pointSize: 8)
let mySymbolImage = UIImage(systemSymbol: .zSquare, withConfiguration: myConfig) 
let mySymbolImageConfig = mySymbolImage.configuration // of type UIImage.Configuration
let mySymbolImage2WithSameConfig = UIImage(systemSymbol: .zSquareFill, withConfiguration: mySymbolImageConfig)
```
