### ISSUE TITLE
Issues with static_framework = true in SFSafeSymbols.podspec

### ISSUE THREAD

**Issue by zaggo** [SFSafeSymbols/SFSafeSymbols#78]
Is there a reason, why the _SFSafeSymbols.podspec_ contains the `static_framework = true` line?

I try to use SFSymbols in a larger project, where SFSafeSymbols is needed in a private framework (and private Cocoapod). As soon as I add SFSafeSymbols as dependency to the private frameworks podspec file, I'll get an error when I try to `pod update` the main project:

`… target has transitive dependencies that include statically linked binaries: (SFSafeSymbols)`

I tried to comment out the `static_framework = true` line in a fork of SFSafeSymbols and this solves the problem. But I'd prefer to set the dependency to the main repo of SFSafeSymbols and not needing to maintain the fork…

So is there an important reason for the `static_framework = true` in the first place?
Or is there another solution for the issue (and no, I cannot just switch to SPM for many reasons)?

**Comment by fredpi** [comment]
@zaggo Thanks for raising this issue.

I put `static_framework = true` into the pod spec because in the `Package.swift`, the framework has been specified as static.

However, in https://github.com/piknotech/SFSafeSymbols/pull/61, a dynamic variant has been added to the `Package.swift`, so I'm wondering whether that's also possible for the pod spec. Unfortunately, I'm no expert there... Do you know whether that would be possible?
